kind: Added
body: 'vault: optional vaultInitSecret.enabled flag deploys a Role + RoleBinding and writes vault init data (unseal keys + root token) to a Kubernetes Secret for easier backup and recovery'
time: 2026-04-11T00:00:00.000000000+00:00
custom:
    Ref: Pull
    RefID: "256"
