---
# Add /etc/hosts entries so that plugin service hostnames are resolvable
# from any host (especially cycloid-api on core hosts).

- name: Add cycloid-plugins-registry to /etc/hosts | cycloid-plugins dns
  lineinfile:
    path: /etc/hosts
    regexp: '.*cycloid-plugins-registry$'
    line: "{{ cycloid_plugins_host }} cycloid-plugins-registry"
    state: present

- name: Add cycloid-plugins-manager to /etc/hosts | cycloid-plugins dns
  lineinfile:
    path: /etc/hosts
    regexp: '.*cycloid-plugins-manager$'
    line: "{{ cycloid_plugins_host }} cycloid-plugins-manager"
    state: present

- name: Add cycloid-plugins-docker-registry to /etc/hosts | cycloid-plugins dns
  lineinfile:
    path: /etc/hosts
    regexp: '.*cycloid-plugins-docker-registry$'
    line: "{{ cycloid_plugins_host }} cycloid-plugins-docker-registry"
    state: present
  when: cycloid_plugins_docker_registry_enabled|bool
