---

- name: Stop services | seaweedfs
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - seaweedfs_container
    - docker
    - docker.socket
  failed_when: false

- name: Remove packages | seaweedfs
  package:
    name:
      - docker*
    state: absent
  failed_when: false
  when: setup_packages

- name: Remove files | seaweedfs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ seaweedfs_config_path }}"
    - "{{ cycloid_install_path }}"
    - /etc/systemd/system/seaweedfs_container.service
    - /etc/default/seaweedfs
    - /etc/sysconfig/seaweedfs
    - /etc/systemd/system/docker.service
    - /var/lib/docker
    - /opt/containerd

- name: Force systemd to reread configs | seaweedfs
  systemd:
    daemon_reload: yes

- name: systemctl reset-failed | seaweedfs
  shell: systemctl reset-failed
