{{- if .Values.ai.enabled }}
{{- $secretName := printf "%s-ai" (include "cycloid.fullname" .) }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $chromadbAuthToken := "" }}
{{- if $existingSecret }}
  {{- $chromadbAuthToken = index $existingSecret.data "chromadb-auth-token" | b64dec }}
{{- else }}
  {{- $chromadbAuthToken = .Values.ai.chromadb.authToken | default (randAlphaNum 64) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cycloid.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  chromadb-auth-token: {{ $chromadbAuthToken | b64enc | quote }}
  mistral-api-key: {{ .Values.ai.mistralApiKey | b64enc | quote }}
{{- end }}
