{{- if and .Values.plugins.enabled .Values.plugins.dockerRegistry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plugins.dockerRegistry.fullname" . }}
  labels:
    {{- include "cycloid.labels" . | nindent 4 }}
    {{- include "plugins.dockerRegistry.selectorLabels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "plugins.dockerRegistry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plugins.dockerRegistry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plugins.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plugins.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: registry-auth
          secret:
            secretName: {{ include "plugins.dockerRegistry.secretName" . }}
            items:
              - key: REGISTRY_BCRYPT_PASSWORD
                path: htpasswd
        - name: registry-storage
          persistentVolumeClaim:
            claimName: {{ include "plugins.dockerRegistry.fullname" . }}
      containers:
        - name: docker-registry
          image: "{{ .Values.plugins.dockerRegistry.image.repository }}:{{ .Values.plugins.dockerRegistry.image.tag }}"
          imagePullPolicy: {{ .Values.plugins.dockerRegistry.image.pullPolicy }}
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: {{ .Values.plugins.dockerRegistry.username | quote }}
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: registry-auth
              mountPath: /auth
              readOnly: true
            - name: registry-storage
              mountPath: /var/lib/registry
          resources:
            {{- toYaml .Values.plugins.dockerRegistry.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugins.dockerRegistry.fullname" . }}
  labels:
    {{- include "cycloid.labels" . | nindent 4 }}
    {{- include "plugins.dockerRegistry.selectorLabels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "plugins.dockerRegistry.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plugins.dockerRegistry.fullname" . }}
  labels:
    {{- include "cycloid.labels" . | nindent 4 }}
    {{- include "plugins.dockerRegistry.selectorLabels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.plugins.dockerRegistry.persistence.storageClass }}
  storageClassName: {{ .Values.plugins.dockerRegistry.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.plugins.dockerRegistry.persistence.size }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plugins.dockerRegistry.configMapName" . }}
  labels:
    {{- include "cycloid.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  hosts.toml: |
    server = "http://{{ include "plugins.dockerRegistry.fullname" . }}:5000"

    [host."http://{{ include "plugins.dockerRegistry.fullname" . }}:5000"]
      capabilities = ["pull", "resolve"]
      skip_verify = true
{{- end }}
