{{- if and .Values.plugins.enabled .Values.plugins.dockerRegistry.enabled }}
{{- $secretName := include "plugins.dockerRegistry.secretName" . }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $password := "" }}
{{- $bcryptHash := "" }}
{{- if $existingSecret }}
  {{- $password = index $existingSecret.data "REGISTRY_PASSWORD" | b64dec }}
  {{- $bcryptHash = index $existingSecret.data "REGISTRY_BCRYPT_PASSWORD" | b64dec }}
{{- else }}
  {{- $password = randAlphaNum 30 }}
  {{- $bcryptHash = htpasswd .Values.plugins.dockerRegistry.username $password }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cycloid.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  REGISTRY_URI: {{ printf "%s.%s.svc.cluster.local:5000" (include "plugins.dockerRegistry.fullname" .) .Release.Namespace | b64enc | quote }}
  REGISTRY_USERNAME: {{ .Values.plugins.dockerRegistry.username | b64enc | quote }}
  REGISTRY_PASSWORD: {{ $password | b64enc | quote }}
  REGISTRY_BCRYPT_PASSWORD: {{ $bcryptHash | b64enc | quote }}
{{- end }}
