{{- if and .Values.plugins.enabled .Values.plugins.dockerRegistry.enabled (not .Values.plugins.dockerRegistry.existingSecret) (not .Values.plugins.dockerRegistry.existingPullSecret) }}
{{- $secretName := include "plugins.dockerRegistry.secretName" . }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $password := "" }}
{{- if $existingSecret }}
  {{- $password = index $existingSecret.data "REGISTRY_PASSWORD" | b64dec }}
{{- else }}
  {{- $password = randAlphaNum 30 }}
{{- end }}
{{- $registryHost := include "plugins.dockerRegistry.registryURI" . }}
{{- $username := .Values.plugins.dockerRegistry.username }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}
{{- $dockercfg := printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $registryHost $username $password $auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-docker-registry-pull" (include "cycloid.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cycloid.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockercfg | b64enc | quote }}
{{- end }}
