{{- if .Values.plugins.enabled }}
{{- range $name, $instance := .Values.plugins.pluginRegistry.instances }}
{{- $useLocal := true }}
{{- if hasKey $instance "use_local_registry" }}
  {{- $useLocal = $instance.use_local_registry }}
{{- end }}
{{- if and (not $useLocal) (not (hasKey $instance "existingSecret")) }}
{{- $secretName := "" }}
{{- if eq $name "default" }}
  {{- $secretName = include "plugins.pluginRegistry.fullname" $ }}
{{- else }}
  {{- $secretName = printf "%s-plugin-registry-%s" (include "cycloid.fullname" $) $name | trunc 63 | trimSuffix "-" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "cycloid.labels" $ | nindent 4 }}
    {{- with $.Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  REGISTRY_URI: {{ $instance.registry_uri | default "" | b64enc | quote }}
  REGISTRY_USERNAME: {{ $instance.registry_username | default "" | b64enc | quote }}
  REGISTRY_PASSWORD: {{ $instance.registry_password | default "" | b64enc | quote }}
---
{{- end }}
{{- end }}
{{- end }}
