{{- if .Values.vault.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cycloid.vaultInitScriptConfigMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cycloid.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  init.sh: |
{{ include "cycloid.vaultInitScript" . | indent 4 }}
{{- end }}
