---
version: "4"
name: "On-premise"
canonical: "cycloid-onprem"
status: "private"
description: "Create On-premise setup of Cycloid."
keywords:
- "cycloid"
- "concourse"
- "worker"
- "elasticsearch"
- "docker"
- "ses"
- "vault"
- "redis"
- "provider:aws"
author: "Cycloid"
image: "https://static.cycloid.io/docker.svg"
technologies:
- technology: "cycloid-core"
  version: "n/a"
- technology: "redis"
  version: "n/a"
- technology: "mysql"
  version: "5.7.x"
- technology: "vault"
  version: "n/a"
- technology: "concourse"
  version: "7.9.1"
- technology: "postgres"
  version: "n/a"
- technology: "concourse-worker"
  version: "7.9.1"

config:
  # define the default pipeline here
  default:
    name: "AWS ec2 instances"
    description: "Setup onprem on aws ec2 instances."
    pipeline:
      pipeline:
        path: "pipeline/pipeline.yml"
      variables:
        path: "pipeline/variables.sample.yml"
        destination: "($ .config_root $)/pipeline/variables.yml"
    terraform:
      onprem:
        path: "terraform/main.tf.sample"
        destination: "($ .config_root $)/terraform/main.tf"
    ansible:
      onprem:
        path: "ansible/environments/cycloid.yml.sample"
        destination: "($ .config_root $)/ansible/environments/cycloid-($ .environment $).yml"
