---
version: '2'
name: 'onprem'
canonical: 'stack-onprem'
status: 'private'
description: 'Create onprem setup of cycloid.'
keywords:
  - 'cycloid'
  - 'concourse'
  - 'worker'
  - 'minio'
  - 'docker'
  - 'ses'
  - 'provider:aws'
author: 'Cycloid'
image: ''
technologies:
  - technology: cycloid-core
    version: n/a
  - technology: minio
    version: n/a
  - technology: redis
    version: n/a
  - technology: mysql
    version: 5.7.x
  - technology: vault
    version: n/a
  - technology: concourse
    version: 6.7.6
  - technology: postgres
    version: n/a
  - technology: concourse-worker
    version: 6.7.6
config:
  # define the default pipeline here
  default:
    name: 'AWS ec2 instances'
    description: 'Setup onprem on aws ec2 instances.'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      onprem:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
    ansible:
      onprem:
        path: 'ansible/environments/cycloid.yml.sample'
        destination: '($ project $)/ansible/environments/cycloid-($ environment $).yml'
