---
default:
  pipeline:
    Terraform:
      - name: "AWS access key"
        description: "Amazon AWS access key for Terraform."
        key: aws_access_key
        widget: cy_cred
        type: string
        default: "((aws_admin.access_key))"
      - name: "AWS secret key"
        description: "Amazon AWS secret key for Terraform."
        key: aws_secret_key
        widget: cy_cred
        type: string
        default: "((aws_admin.secret_key))"
      - name: "Amazon AWS region"
        description: "Amazon AWS region to use for Terraform."
        key: aws_default_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
      - name: "Terraform storage bucket"
        description: "AWS S3 bucket name to store terraform remote state file."
        key: terraform_storage_bucket_name
        widget: simple_text
        type: string
        default: cycloid-terraform-remote-state
    Repos:
      - name: "Config repository"
        key: config_git_repository
        type: string
        widget: cy_crs
        description: "Git repository URL containing the config of the stack."
        default: "git@github.com:cycloidio/cycloid-stacks-test.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        widget: cy_cred
        default: "((git_github.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: config_git_branch
        widget: cy_branch
        type: string
        description: "The branch used by the config repository"
        source: config_git_repository
        default: "config"
        required: true
    Cycloid:
      - name: "Stack branch"
        description: "Branch to use on the public stack Git repository."
        key: stack_git_branch
        widget: simple_text
        type: string
        default: master
      - name: "Terraform version"
        description: "Terraform version used."
        key: terraform_version
        widget: simple_text
        type: string
        default: '0.15.1'
      - name: "Debug SSH key"
        description: "SSH pubkey injected by packer during the ec2 ami build. Used only to debug failure."
        key: debug_public_key
        widget: text_area
        type: string
        default: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAsxJseuZAPIQetH6lZGYFHIW/uRKM6wgwVIUwZ+/EsrnUMcJA3GC+ILH4McQtWyv+goA6o7HX2IwXx61qHeT0Xxvh5+oOGAddwLoHERvOQxeZLeWqvbDzOLDr9xLNQri+WGP552kGnP/pDV2m7KRwAPFMwg+zRjAoHblLj1Ztrztb4tExEEFOfVngwu8BX493OowTYLC3BmbOOPVZjMLY81pN5FzRx+i8MB0JsHIxaWaNRY3Yx81o5kiNgMsf8S9mwET9TH2e3yfeNXmjXz5TL+KetimysYPr12QHJyX2J/jwpFCuIn3voNovAsF32Umb7BqHk9RhRF341py5Bi6d3Q=="

  terraform:
    application:
      - name: "Instance count"
        description: "Number of Aws EC2 onprem server to create."
        key: cy_instances_count
        widget: simple_text
        type: string
        default: "2"
      - name: "Instance type"
        description: "Type of Aws EC2 onprem servers."
        key: cy_instances_type
        widget: auto_complete
        type: string
        default: "t3.small"
        values:
            - "t3.micro"
            - "t3.small"
            - "t3.medium"
            - "t3.large"
      - name: "Instance disk size"
        unit: Go
        description: "Disk size of Aws EC2 onprem servers."
        key: cy_instances_disk_size
        widget: slider_range
        type: integer
        default: 50
        values:
            - 10
            - 250
      - name: "Instance EBS optimized"
        description: "Whether the Instance is EBS optimized or not, related to the instance type you choose."
        key: cy_instances_ebs_optimized
        widget: switch
        type: boolean
        default: false
      - name: "Allowed Ips"
        description: "Ip range allowed to connect on servers."
        key: cy_instances_cidr_blocks_allow
        widget: text_area
        type: array
        default:
            - 0.0.0.0/0
      - name: "SSH Keypair to access instances"
        description: "Keypair to access instances."
        key: keypair_name
        widget: auto_complete
        type: string
        default: "cycloid"
        values:
            - "cycloid"
            - "cycloid-dev"
    network:
      - name: "Aws VPC ID"
        description: "Amazon VPC id on which create each components."
        key: vpc_id
        widget: simple_text
        type: string
        default: data.terraform_remote_state.infrastructure.outputs.prod_vpc_id
        required: true
      - name: "Public subnets IDs"
        description: "Public subnet IDs to use for the public ELB load balancer."
        key: public_subnets_ids
        widget: simple_text
        type: string
        default: data.terraform_remote_state.infrastructure.outputs.prod_public_subnets_ids
        required: true
      - name: "Bastion allow security group"
        description: "Amazon source security group ID which will be allowed to connect on fronts port 22 (ssh)."
        key: bastion_sg_allow
        widget: simple_text
        type: string
        default: "data.terraform_remote_state.infrastructure.outputs.prod_bastion_sg_allow"
      - name: "AMI search name pattern (or use Base ami ID directly)"
        description: "Type of Aws EC2 frontend servers."
        key: debian_ami_name
        widget: auto_complete
        type: string
        default: "debian-10-amd64-"
        values:
            - "debian-9-amd64-*"
            - "debian-10-amd64-*"
            - "CentOS 7.9.2009 x86_64*"
            - "CentOS 8.3.2011 x86_64*"
            - "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"
            - "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"
      - name: "Base ami ID"
        description: "Type of Aws EC2 frontend servers."
        key: base_ami_id
        widget: auto_complete
        type: string
        default: ""
        values:
            - "ami-0874dad5025ca362c"
            - "ami-04f5641b0d178a27a"
            - "ami-0a75a5a43b05b4d5f"
            - "ami-0e9968d81cef18781"
            - "ami-01aa664a17515f5bb"
  ansible:
    configuration:
      - name: "Licence"
        description: "Cycloid Licence."
        key: cycloid_licence
        widget: simple_text
        type: string
        default: ""
