---
version: "2"
use_cases:
- name: default
  sections:
  - name: General
    groups:
    - name: Common
      technologies: [pipeline]
      vars:
        - name: Display Cycloid advanced options
          description: Check to see Cycloid advanced options to configure your project.
          key: advanced_opt
          widget: switch
          type: boolean
          default: true

    - name: Product
      technologies: [ansible, pipeline]
      vars:
        - name: "Cycloid API image"
          description: "Provide the Docker image tag to use."
          key: cycloid_api_tag
          widget: auto_complete
          type: string
          default: "prod"
          values:
              - "prod"
              - "staging"
        - name: "Cycloid Frontend image"
          description: "Provide the Docker image tag to use.."
          key: cycloid_frontend_tag
          widget: auto_complete
          type: string
          default: "prod"
          values:
              - "prod"
              - "staging"
    - name: Product-advanced-options
      technologies: [ansible]
      condition: advanced_opt==true
      vars:
        - name: "Cycloid API images repository"
          description: "Cycloid API images repository."
          key: cycloid_api_repo
          widget: auto_complete
          type: string
          default: "rg.fr-par.scw.cloud/cycloidio/cycloid-backend"
          values:
              - "661913936052.dkr.ecr.eu-west-1.amazonaws.com/youdeploy-http-api"
              - "rg.fr-par.scw.cloud/cycloidio/cycloid-backend"
        - name: "Cycloid Frontend images repository"
          description: "Cycloid Frontend images repository."
          key: cycloid_frontend_repo
          widget: auto_complete
          type: string
          default: "rg.fr-par.scw.cloud/cycloidio/cycloid-frontend"
          values:
              - "661913936052.dkr.ecr.eu-west-1.amazonaws.com/youdeploy-frontend"
              - "rg.fr-par.scw.cloud/cycloidio/cycloid-frontend"

    - name: Licence
      # TODO: not supported
      # condition: cycloid_api_tag != "prod"
      # condition: cycloid_api_tag==staging
      technologies: [pipeline]
      vars:
        - name: "Cycloid Licence"
          description: "Cycloid Licence."
          key: cycloid_licence
          type: string
          widget: cy_cred
          default: "((custom_onprem_licence.prod))"

    - name: Stack
      # This variable need to be write when using onprem (not playground)
      # condition: advanced_opt==true
      technologies: [pipeline]
      vars:
        - name: "Stack branch"
          description: "Branch to use on the public stack Git repository."
          key: stack_git_branch
          widget: simple_text
          type: string
          default: master

    - name: Service-pipeline
      technologies: [pipeline]
      vars:
        - name: "Concourse worker enabled"
          description: "Install a concourse worker"
          key: install_concourse_worker
          widget: switch
          type: boolean
          default: false
        - name: "Elasticsearch (CCM) enabled"
          description: "Install Elasticsearch (used for CCM. Required dedicated instance or a bigger mutu)"
          key: install_elasticsearch
          widget: switch
          type: boolean
          default: false

        - name: "Ansible extra variables"
          description: "Cycloid EXTRA_ANSIBLE_VARS"
          key: ansible_params_extravars
          widget: text_area
          type: map
          default:
            test: "foo"
            #azure_ad_tenant_id: ""
            #azure_ad_client_id: ""
            #google_client_id: ""
            #google_client_secret: ""
            #github_host_address: "https://api.github.com"
            #github_client_id: ""
            #github_client_secret: ""

    - name: Service-ansible
      technologies: [ansible]
      vars:
        - name: "SAML Auth enable"
          description: "Enable SAML or not."
          key: saml_auth_enabled
          widget: switch
          type: boolean
          default: false
    - name: External authentification
      condition: saml_auth_enabled==true
      technologies: [ansible]
      vars:
        - name: "SAML IDP Metadata URL"
          description: "SAML IDP Metadata URL. (if SAML enabled)"
          key: saml_idp_metadata_url
          widget: auto_complete
          type: string
          default: "https://samltest.id/saml/idp"
          values:
              - "https://samltest.id/saml/idp"

    - name: Service-ansible-opt
      condition: advanced_opt==true
      technologies: [ansible]
      vars:
        - name: "Cycloid Database image"
          description: "Cycloid Database image."
          key: cycloid_db_image
          widget: auto_complete
          type: string
          default: "bitnami/mysql:8.0.36"
          values:
              - "mysql:8.0.35"
              - "mariadb:10.2.11"

  # Use local ES, if needed can be exposed via extra vars
  # - name: Features
  #   groups:
  #   - name: Cloud Cost Management
  #     condition: advanced_opt==true
  #     technologies: [ansible]
  #     vars:
  #       - name: "Elasticsearch URL"
  #         description: "Elasticsearch database URL for Cloud Cost Management"
  #         key: cost_explorer_es_url
  #         widget: simple_text
  #         type: string
  #         default: ""
  #         required: false
  #       - name: "Elasticsearch username"
  #         description: "Elasticsearch database username for Cloud Cost Management"
  #         key: cost_explorer_es_username
  #         widget: simple_text
  #         type: string
  #         default: ""
  #         required: false
  #       - name: "Elasticsearch password"
  #         description: "Elasticsearch database password for Cloud Cost Management"
  #         key: cost_explorer_es_password
  #         widget: simple_text
  #         type: string
  #         default: ""
  #         required: false
  #       - name: "Elasticsearch disable TLS verification"
  #         description: "Disable TLS verification on Elasticsearch for Cloud Cost Management"
  #         key: cost_explorer_es_insecure_skip_tls
  #         widget: switch
  #         type: boolean
  #         default: true

  - name: Infrastructure
    groups:
    - name: terraform
      technologies: [terraform]
      vars:
        - name: "Instance count"
          description: "Number of Aws EC2 onprem server to create."
          key: cy_instances_count
          widget: number
          type: integer
          default: 1
        - name: "Instance type"
          description: "Type of Aws EC2 onprem servers."
          key: cy_instances_type
          widget: auto_complete
          type: string
          default: "t3.small"
          values:
              - "t3.micro"
              - "t3.small"
              - "t3.medium"
              - "t3.large"

        - name: "AMI search name pattern (or use Base ami ID directly)"
          description: "Type of Aws EC2 frontend servers."
          key: debian_ami_name
          widget: auto_complete
          type: string
          default: "debian-11-amd64-*"
          values:
              - "debian-11-amd64-*"
              - "debian-12-amd64-*"
              - "CentOS 8.3.2011 x86_64*"
              - "ubuntu/images/hvm-ssd/ubuntu-focal-22.04-amd64-server-*"
        - name: "Base ami ID (optional)"
          description: "Type of Aws EC2 frontend servers."
          key: base_ami_id
          widget: auto_complete
          type: string
          default: ""
          values:
              - "ami-0ad0923fe3bd430fa"

    - name: terraform-opt
      technologies: [terraform]
      vars:
        - name: "Instance disk size"
          unit: Go
          description: "Disk size of Aws EC2 onprem servers."
          key: cy_instances_disk_size
          widget: slider_range
          type: integer
          default: 60
          values:
              - 10
              - 250
        - name: "Instance EBS optimized"
          description: "Whether the Instance is EBS optimized or not, related to the instance type you choose."
          key: cy_instances_ebs_optimized
          widget: switch
          type: boolean
          default: false
        - name: "Allowed Ips"
          description: "Ip range allowed to connect on servers."
          key: cy_instances_cidr_blocks_allow
          widget: text_area
          type: array
          default:
              - 0.0.0.0/0
        - name: "SSH Keypair to access instances"
          description: "Keypair to access instances."
          key: keypair_name
          widget: auto_complete
          type: string
          default: "cycloid"
          values:
              - "cycloid"
