---
- name: Install depends
  hosts: cycloid_core,cycloid_db,cycloid_creds,cycloid_scheduler,cycloid_scheduler_db
  gather_facts: no
  tasks:

    # Ensure we use vfs storage (not aufs)
    - name: ensure /etc/docker exist
      file:
        path: "/etc/docker"
        state: directory
        mode: 0750
        recurse: yes
    - name: for docker to use vfs storage
      copy:
        content: '{"storage-driver": "vfs"}'
        dest: "/etc/docker/daemon.json"

    - name: install apt depends
      apt:
        name:
        - net-tools
        - lsb-release
        - curl
        - procps
        - python-setuptools
        - python-pip
        state: present

    - name: install pip depends
      pip:
         name:
           - pip
           - docker
         state: latest
