# YAML anchors
shared:

  # Task : sync and merge with rsync 2 rep. Used to merge stack and config
  - &merge-stack-and-config
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: cycloid/cycloid-toolkit
        tag: latest
    run:
      path: /usr/bin/merge-stack-and-config
    outputs:
    - name: merged-stack
      path: "merged-stack"

  - &run-ansible
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cycloid/cycloid-toolkit
          tag: "((ansible_version))"
      run:
        path: /usr/bin/ansible-runner
      caches:
        - path: ansible-playbook/roles
      inputs:
      - name: merged-stack
        path: ansible-playbook
groups:

- name: overview
  jobs:
  - terraform-plan
  - terraform-apply
  - install-ansible

- name: setup
  jobs:
  - install-ansible

- name: infra
  jobs:
  - terraform-plan
  - terraform-apply

- name: destroy
  jobs:
  - terraform-destroy

resource_types:

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: ((terraform_version))

resources:

- name: tfstate
  type: terraform
  icon: terraform
  source:
    env_name: ((env))
    backend_type: s3
    backend_config:
      bucket: ((terraform_storage_bucket_name))
      key: ((project))-((env)).tfstate
      workspace_key_prefix: ((project))
      region: ((aws_default_region))
      access_key: ((aws_access_key))
      secret_key: ((aws_secret_key))
    vars:
      access_key: ((aws_access_key))
      secret_key: ((aws_secret_key))
      env: ((env))
      project: ((project))
      customer: ((customer))
      aws_region: ((aws_default_region))
    env:
      AWS_ACCESS_KEY_ID: ((aws_access_key))
      AWS_DEFAULT_REGION: ((aws_default_region))
      AWS_SECRET_ACCESS_KEY: ((aws_secret_key))

# The Terraform stack (will be merged with the config)
- name: git_stack-terraform
  icon: github-circle
  type: git
  source:
    uri: git@github.com:cycloidio/ansible-cycloid-onprem.git
    branch: ((stack_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - stack-onprem/terraform/*

- name: git_stack-ansible
  icon: github-circle
  type: git
  source:
    uri: git@github.com:cycloidio/ansible-cycloid-onprem.git
    branch: ((stack_git_branch))
    private_key: ((config_git_private_key))
    ignore_paths:
      - stack-onprem/terraform/*
      - stack-onprem/pipeline/*

# The Terraform config (will be merged with the stack)
- name: git_config-terraform
  type: git
  icon: github-circle
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - ((config_terraform_path))/*

- name: git_config-ansible
  type: git
  icon: github-circle
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - ((config_ansible_path))/environments/*

jobs:

# Merge and trigger a plan whenever there is a commit in Terraform stack or config
- name: terraform-plan
  serial: True
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_stack-terraform
        params: {depth: 1}
        trigger: true
      - get: git_config-terraform
        params: {depth: 1}
        trigger: true

      - task: merge-stack-and-config
        config:
          <<: *merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
        params:
          CONFIG_PATH: ((config_terraform_path))
          STACK_PATH: stack-onprem/terraform

      - put: tfstate
        params:
          plan_only: true
          terraform_source: merged-stack/

# Merge and trigger an apply manually (no autostart of this job)
- name: terraform-apply
  serial: True
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_stack-terraform
        trigger: false
        passed:
          - terraform-plan
      - get: git_config-terraform
        trigger: false
        passed:
          - terraform-plan
      - get: tfstate
        trigger: false
        passed:
          - terraform-plan

      - task: merge-stack-and-config
        config:
          <<: *merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
        params:
          CONFIG_PATH: ((config_terraform_path))
          STACK_PATH: stack-onprem/terraform

      - put: tfstate
        params:
          plan_run: true
          terraform_source: merged-stack/

- name: terraform-destroy
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
        - get: git_stack-terraform
          params: {depth: 1}
          trigger: false
        - get: git_config-terraform
          params: {depth: 1}
          trigger: false
        - task: merge-stack-and-config
          config:
            <<: *merge-stack-and-config
            inputs:
            - name: git_config-terraform
              path: "config"
            - name: git_stack-terraform
              path: "stack"
          params:
            CONFIG_PATH: ((config_terraform_path))
            STACK_PATH: stack-onprem/terraform

        - put: tfstate
          params:
            action: destroy
            terraform_source: merged-stack/
          get_params:
            action: destroy



- name: install-ansible
  serial: True
  build_logs_to_retain: 10
  plan:
  - do:
    - get: git_stack-ansible
      params: {depth: 1}
      trigger: true

    - get: git_config-ansible
      params: {depth: 1}
      trigger: true

    - get: tfstate
      passed:
        - terraform-apply
      trigger: false

    - task: merge-stack-and-config
      config:
        <<: *merge-stack-and-config
        inputs:
        - name: git_config-ansible
          path: "config"
        - name: git_stack-ansible
          path: "stack"
        - name: tfstate
          path: "terraform"
      params:
        CONFIG_PATH: ((config_ansible_path))
        STACK_PATH: ansible

    - task: inventory
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: v2.9
        run:
          path: /bin/bash
          args:
          - -xc
          - |
            DIR=${PWD}
            sleep 300
            exit 1
        inputs:
          - name: merged-stack
          - name: tfstate

#    - task: run-ansible
#      <<: *run-ansible-from-bastion
#      params:
#        SSH_PRIVATE_KEY: ((bastion_private_key_pair))
#        ANSIBLE_VAULT_PASSWORD: ((ansible_vault_password))
#        AWS_DEFAULT_REGION: ((aws_default_region))
#        AWS_ACCESS_KEY_ID: ((aws_access_key))
#        AWS_SECRET_ACCESS_KEY: ((aws_secret_key))
#        ANSIBLE_PLAYBOOK_PATH: ansible-playbook
#        ANSIBLE_PLAYBOOK_NAME: lemp.yml
#        ANSIBLE_FORCE_GALAXY: false
#        EXTRA_ANSIBLE_VARS:
#          customer: ((customer))
#          project: ((project))
#          env: ((env))
#          default_ec2_region: ((aws_default_region))
#          aws_default_region: ((aws_default_region))
#        TAGS:
#          - deploy
