---
groups:
- name: status
  jobs:
  - rds
  - ec2
  - asg
- name: manual
  jobs:
  - start
  - stop
- name: scheduled
  jobs:
  - cron-stop
- name: Overview all
  jobs:
  - cron-stop
  - start
  - stop
  - rds
  - ec2
  - asg
resource_types:
- name: cron-resource
  type: registry-image
  source:
    repository: cycloid/cron-resource
- name: keyval
  type: registry-image
  source:
    repository: swce/keyval-resource
resources:
- name: stop
  type: cron-resource
  source:
    expression: 00 19 * * *
    location: Europe/Paris
    fire_immediately: false
- name: trigger
  type: keyval
jobs:
- name: start
  build_logs_to_retain: 3
  plan:
  - do:
    - task: start
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: busybox
            tag: latest
        run:
          path: "/bin/sh"
          args:
          - "-ec"
          - 'echo "action=start" > output/keyval.properties'
        outputs:
        - name: output
    - put: trigger
      params:
        file: output/keyval.properties
- name: stop
  build_logs_to_retain: 3
  plan:
  - do:
    - task: stop
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: busybox
            tag: latest
        run:
          path: "/bin/sh"
          args:
          - "-ec"
          - 'echo "action=stop" > output/keyval.properties'
        outputs:
        - name: output
    - put: trigger
      params:
        file: output/keyval.properties
- name: cron-stop
  build_logs_to_retain: 3
  plan:
  - do:
    - get: stop
      trigger: true
    - task: stop
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: busybox
            tag: latest
        run:
          path: "/bin/sh"
          args:
          - "-ec"
          - 'echo "action=stop" > output/keyval.properties'
        outputs:
        - name: output
    - put: trigger
      params:
        file: output/keyval.properties
- name: rds
  build_logs_to_retain: 3
  plan:
  - do:
    - get: trigger
      trigger: true
    - task: trigger
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          path: "/bin/sh"
          args:
          - "-ec"
          - |
            while IFS= read -r var; do if [ ! -z "$var" ]; then echo "Adding: $var"; export "$var"; fi; done < trigger/keyval.properties
            # Construct command filters from tags
            if [ "$action" = "start" ]; then
                LookingFor="stopped"
            else
                LookingFor="available"
            fi
            filters=""
            for tag in $TAGS; do
              key=${tag%=*}
              value=${tag#*=}
              if [ -z "$filters" ]; then
                filters='contains(TagList[?Key==`'$key'`].Value, `'$value'`)'
                continue
              fi
              filters=$filters' && contains(TagList[?Key==`'$key'`].Value, `'$value'`)'
            done
            echo "trigger $action on :"
            # status available or stopped
            for rds in $(aws rds describe-db-instances --query 'DBInstances[?MultiAZ==`false` && DBInstanceStatus==`'${LookingFor}'`].DBInstanceArn' --output text); do
              matched=$(aws rds list-tags-for-resource --resource-name $rds --query "$filters")
              if [ "$matched" = 'true' ]; then
                # fetch only the user-identified name and not the full ARN
                id=$(echo "$rds" | awk -F ":" '{print $NF}')
                aws rds ${action}-db-instance --db-instance-identifier "$id"
              fi
            done
        inputs:
        - name: trigger
      params:
        TAGS: env=$ENV client=$ORGANIZATION project=$PROJECT cycloid.io="true"
        AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"
        AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
        AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
- name: asg
  build_logs_to_retain: 3
  plan:
  - do:
    - get: trigger
      trigger: true
    - task: trigger
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          path: "/bin/bash"
          args:
          - "-ec"
          - |
            while IFS= read -r var; do if [ ! -z "$var" ]; then echo "Adding: $var"; export "$var"; fi; done < trigger/keyval.properties
            # Construct command filters from tags
            if [ "$action" = "start" ]; then
                filters='DesiredCapacity==`0` && MinSize==`0` && MaxSize==`0`'
            else
                filters='MaxSize!=`0`'
            fi
            for tag in $TAGS; do
              key=${tag%=*}
              value=${tag#*=}
              filters=$filters' && contains(Tags[?Key==`'$key'`].Value, `'$value'`)'
            done
            echo "trigger $action"
            while read asg min max desired; do
              if [ -z "$asg" ]; then continue; fi
              if [ "$action" = "start" ]; then
                if [ "$min" = 'None' ]; then min=1; fi
                if [ "$desired" = 'None' ]; then desired=1; fi
                if [ "$max" = 'None' ]; then max=2; fi
                aws autoscaling update-auto-scaling-group --auto-scaling-group-name $asg --min-size $min --max-size $max --desired-capacity $desired
              else
                aws autoscaling update-auto-scaling-group --auto-scaling-group-name $asg --min-size 0 --max-size 0 --desired-capacity 0
              fi
            done < <(aws autoscaling describe-auto-scaling-groups  --query 'AutoScalingGroups[?'"${filters}"'].[AutoScalingGroupName,Tags[?Key==`MinSize`] | [0].Value,Tags[?Key==`MaxSize`] | [0].Value,Tags[?Key==`DesiredCapacity`] | [0].Value]' --output text)
        inputs:
        - name: trigger
      params:
        TAGS: env=$ENV client=$ORGANIZATION project=$PROJECT cycloid.io="true"
        AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"
        AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
        AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
- name: ec2
  build_logs_to_retain: 3
  plan:
  - do:
    - get: trigger
      passed:
      - asg
      trigger: true
    - task: trigger
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          path: "/bin/sh"
          args:
          - "-ec"
          - |
            while IFS= read -r var; do if [ ! -z "$var" ]; then echo "Adding: $var"; export "$var"; fi; done < trigger/keyval.properties
            # Construct command filters from tags
            if [ "$action" = "start" ]; then
                filters="Name=instance-state-name,Values=stopped"
                pipeline_action=unpause
            else
                filters="Name=instance-state-name,Values=running"
                pipeline_action=pause
            fi
            for tag in $TAGS; do
              key=${tag%=*}
              value=${tag#*=}
              filters="$filters Name=tag:$key,Values=$value"
            done
            echo "trigger $action"
            instances=""
            for instance in $(aws ec2 describe-instances --filters  $filters --query 'Reservations[].Instances[].InstanceId' --output text); do
              instances="${instances} ${instance}"
            done
            if [ -n "$instances" ]; then
              aws ec2 ${action}-instances --instance-ids $instances
            fi

            # Pause/Unpause install-onprem job.
            # It ensure no deploy are done when the infra is stopped, and infra is updated on start
            echo "${pipeline_action} install-onprem job ..."
            cy login --org $ORGANIZATION --api-key $API_KEY
            cy --org $ORGANIZATION pipeline ${pipeline_action}-job --project $PROJECT --env $ENV --job install-onprem
        inputs:
        - name: trigger
      params:
        TAGS: env=$ENV client=$ORGANIZATION project=$PROJECT cycloid.io="true"
        AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"
        AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
        AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
