#!/usr/bin/env bash
# shellcheck shell=sh

# Rewrites the vault approle credentials in values.custom.yaml from the JSON
# files generated by vault-config.sh. Unlike vault-config.sh -- which does a
# one-shot sed on the ##cycloid-*## placeholders -- this script targets the
# YAML keys themselves, so it remains usable after the initial init when the
# placeholders are already gone.

DIR="$(dirname "$(readlink -f "$0")")"
OUTPUT_DIR="$DIR/.out"

# shellcheck source=./cecho-utils.sh
. "$DIR/cecho-utils.sh"

export VALUES_CUSTOM_YAML="${VALUES_CUSTOM_YAML:-./values.custom.yaml}"

if [ ! -f "$VALUES_CUSTOM_YAML" ]; then
  perror "$0 > $VALUES_CUSTOM_YAML file not found"
  exit 1
fi

if ! command -v jq >/dev/null; then
  perror "$0 > jq command not found. Please install it. For example: apt-get install jq"
  exit 1
fi

set -e

for f in cycloid-role-id.json cycloid-secret-id.json cycloid-ro-role-id.json cycloid-ro-secret-id.json; do
  if [ ! -f "$OUTPUT_DIR/$f" ]; then
    perror "$0 > Missing $OUTPUT_DIR/$f -- run vault-config.sh first."
    exit 1
  fi
done

RID=$(jq -r .data.role_id     "$OUTPUT_DIR/cycloid-role-id.json")
SID=$(jq -r .data.secret_id   "$OUTPUT_DIR/cycloid-secret-id.json")
RO_RID=$(jq -r .data.role_id   "$OUTPUT_DIR/cycloid-ro-role-id.json")
RO_SID=$(jq -r .data.secret_id "$OUTPUT_DIR/cycloid-ro-secret-id.json")

for v in RID SID RO_RID RO_SID; do
  eval "val=\$$v"
  if [ -z "$val" ] || [ "$val" = "null" ]; then
    perror "$0 > Could not extract $v from JSON files in $OUTPUT_DIR"
    exit 1
  fi
done

# Verify the target keys exist before mutating. If the file structure has
# diverged from the expected shape, fail loudly rather than no-op silently.
require_pattern() {
  if ! grep -qE "$1" "$VALUES_CUSTOM_YAML"; then
    perror "$0 > Key matching '$1' not found in $VALUES_CUSTOM_YAML"
    exit 1
  fi
}
require_pattern '^[[:space:]]*roleId:'
require_pattern '^[[:space:]]*secretId:'
require_pattern '^[[:space:]]*-[[:space:]]+name:[[:space:]]+VAULT_ROLE_ID'
require_pattern '^[[:space:]]*-[[:space:]]+name:[[:space:]]+VAULT_SECRET_ID'
require_pattern '^[[:space:]]*vaultAuthParam:'

pwarning "$0 > Updating vault approle credentials in $VALUES_CUSTOM_YAML"

# backend.vault.roleId / secretId -- only occurrences of those keys in the chart.
sed -i -E "s|^([[:space:]]*roleId:[[:space:]]*)\"[^\"]*\"(.*)|\1\"$RID\"\2|"   "$VALUES_CUSTOM_YAML"
sed -i -E "s|^([[:space:]]*secretId:[[:space:]]*)\"[^\"]*\"(.*)|\1\"$SID\"\2|" "$VALUES_CUSTOM_YAML"

# Concourse web sidecar env vars -- value is on the line that immediately follows
# the matching `- name:` line. Sed's `n` advances to that next line before subst.
sed -i -E "/^[[:space:]]*-[[:space:]]+name:[[:space:]]+VAULT_ROLE_ID[[:space:]]*$/{n;s|^([[:space:]]*value:[[:space:]]*)\"[^\"]*\"(.*)|\1\"$RO_RID\"\2|;}"   "$VALUES_CUSTOM_YAML"
sed -i -E "/^[[:space:]]*-[[:space:]]+name:[[:space:]]+VAULT_SECRET_ID[[:space:]]*$/{n;s|^([[:space:]]*value:[[:space:]]*)\"[^\"]*\"(.*)|\1\"$RO_SID\"\2|;}" "$VALUES_CUSTOM_YAML"

# concourse.secrets.vaultAuthParam -- single key, full value rewritten.
sed -i -E "s|^([[:space:]]*vaultAuthParam:[[:space:]]*)\"[^\"]*\"(.*)|\1\"role_id:$RO_RID,secret_id:$RO_SID\"\2|" "$VALUES_CUSTOM_YAML"

psuccess "$0 > $VALUES_CUSTOM_YAML updated. Please re-run 'helm upgrade'."
